FROM        --platform=$TARGETOS/$TARGETARCH alpine:latest

LABEL       author="Silly Development" maintainer="gamer@sillydev.co.uk"

RUN         apk add --update --no-cache ca-certificates curl unzip tar git jq wget
